name: Testing codes

on:
  push:
  pull_request:

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.10']
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        architecture: x64
        python-version: ${{ matrix.python-version }}
    - uses: abatilo/actions-poetry@v2.0.0
    - name: Install dependencies
      run: poetry install
    - name: Run test
      run: |
        poetry run python -m pytest --doctest-glob="README.rst"
